name: Generer APK de Test

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configuration de Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Configuration de Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Créer le squelette Android manquant
        run: flutter create --platforms=android .

      - name: Récupération des packages
        run: flutter pub get

      - name: Compilation de l'APK
        run: flutter build apk --debug

      - name: Téléverser l'application
        uses: actions/upload-artifact@v4
        with:
          name: app-release-preview
          path: build/app/outputs/flutter-apk/app-debug.apk
